// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Package generator produces the bridge artifacts that connect
// Aspire's Bicep output to azd's deployment model.
package generator

import (
	"fmt"
	"os"
	"strings"

	"microsoft.aspire/internal/pkg/aspire"
)

// GenerateAzureYaml creates an azure.yaml file from the manifest services.
// Only services that have a containerImage param are included — these are
// buildable services that need `aspire do push`. Pre-built containers (like
// Redis) are deployed directly by their Bicep modules via main.bicep.
//
// The `aspire:` section stores the AppHost path in AdditionalProperties,
// which flows through gRPC to lifecycle event handlers for detection.
func GenerateAzureYaml(projectName string, appHostRelPath string, services []aspire.ServiceInfo, outputPath string) error {
	var sb strings.Builder

	sb.WriteString("# Generated by azd aspire init — do not edit manually\n")
	sb.WriteString(fmt.Sprintf("name: %s\n", projectName))
	sb.WriteString("aspire:\n")
	sb.WriteString(fmt.Sprintf("  appHost: %s\n", appHostRelPath))
	sb.WriteString("services:\n")

	hasServices := false
	for _, svc := range services {
		// Only include services that need image push (have a containerImage param)
		if svc.ImageParam == "" {
			continue
		}
		envName := aspire.ToEnvVarName(svc.Name)
		sb.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
		sb.WriteString(fmt.Sprintf("    image: ${SERVICE_%s_IMAGE_NAME}\n", envName))
		sb.WriteString("    host: containerapp\n")
		hasServices = true
	}

	if !hasServices {
		return fmt.Errorf("no buildable services found in manifest (no containerImage params)")
	}

	sb.WriteString("infra:\n")
	sb.WriteString("  path: ./infra\n")

	// Skip package step — images are built and pushed by `aspire do push`
	// during postprovision, not by azd package.
	sb.WriteString("workflows:\n")
	sb.WriteString("  up:\n")
	sb.WriteString("    - azd: provision\n")
	sb.WriteString("    - azd: deploy --all\n")

	//nolint:gosec // outputPath is within the user's project directory
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write azure.yaml: %w", err)
	}

	return nil
}
